# Generated by Django 3.2.4 on 2021-06-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planbapi', '0002_alter_event_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='customer',
            new_name='user',
        ),
    ]
